import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { AnimationOnScroll } from 'react-animation-on-scroll';

export default function Home() {
  return (
    <div className>
      <Head>
        <title>ET Site Mockup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <div id="Hero" className="relative w-full h-[90vh] overflow-hidden">
            <video autoPlay muted loop className = "absolute object-cover w-full h-full">
              <source src="/videos/background.mp4"
              type="video/mp4"/>
            </video>
            <div className="relative flex flex-col w-full h-full overflow-hidden">
              <AnimationOnScroll animateIn="animate__fadeIn" initiallyVisible="false" offset={0}>
              <div id="logo+nav" className="px-6 py-2 flex justify-between items-center">
                <Image src="/ETPNGWhite.webp" width="150px" height="80px"></Image>
                <Image src="/burger.png" width="20px" height="20px" layout="fixed"></Image>

              </div>
              </AnimationOnScroll>
              <div className="px-6 text-5xl font-bold text-white w-6/7 mt-[80px] text">Next Level IT and End-User Security</div>
              <div className="px-6 text-md font-light text-white w-5/6 mt-[25px]">We are a client-focused, standards-based, end-to-end IT consulting company providing the services and skills to secure IT infrastructures and networks critical to our nation's security</div>
            </div>
          </div>  
          <div id="about-us-content" className="px-8 mt-40 w-full bg-gray-100 py-6 overflow-x-hidden flex flex-col items-center">
            <Image src="/AboutUs.webp" width="370" height="370vw" layout="fixed"></Image>
            <div className=" w-full mt-5">
              <p className="text-2xl font-bold text-left">About Us</p>
              <div className="text-md text-gray-500s mt-4 text-justify tracking-tighter">
                We are proud to be disruptive consultants. We don’t waste our time with traditional corporate politics – we prioritize employee voices, collaboration, and climate. We understand the importance of workplace culture and a sense of belonging and purpose.
                <br/>
                <br/>
                We serve as Solution Experts to ensure our clients’ systems are secure, efficient, and compliant.</div>
            </div>
          </div>
      </main>

      <footer>
      
      </footer>
    </div>
  )
}
